/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AuLinkTable: typeof import('./src/components/AuLinkTable.vue')['default']
    AuSettings: typeof import('./src/components/AuSettings.vue')['default']
    AuTools: typeof import('./src/components/AuTools.vue')['default']
    Greet: typeof import('./src/components/Greet.vue')['default']
    ServerTable: typeof import('./src/components/ServerTable.vue')['default']
    ServerUpdate: typeof import('./src/components/ServerUpdate.vue')['default']
  }
}
